baseURL = "https://j20232.github.io/"
languageCode = "en-us"
title = "mocobt"
theme = "mine"
canonifyurls = true
hasCJKLanguage = true
publishdir = "public"


[params]
  author = "mocobt"
  avatar = "avatar.jpg"
  favicon = "favicon.ico"

[outputs]
  section = ["JSON", "HTML"]

[[menu.background]]
  pre = "2019-"
  name = "R&D (CV&CG) @ ğŸŒº"
  weight = 105

[[menu.background]]
  pre = "2018"
  name = "R&D (HCI) @ ğŸ‡¯ğŸ‡µ"
  weight = 110

[[menu.background]]
  pre = "2012-2018"
  name = "MEng (HCI) @ ğŸ¦"
  weight = 115

[[menu.field]]
  name = "ğŸ“¸ Optics"
  weight = 5

[[menu.field]]
  name = "âœï¸ Photo retouching"
  weight = 10

[[menu.field]]
  name = "ğŸ’¡ Physically-based rendering"
  weight = 15

[[menu.interest]]
  name = "ğŸ¨ Painting and retouching"
  weight = 5

[[menu.interest]]
  name = "ğŸ‘€ Visual perception"
  weight = 10

[[menu.interest]]
  name = "ğŸ¤š Multi-modal UIs"
  weight = 20

[[menu.interest]]
  name = "ğŸ° Fabrication"
  weight = 40

[[menu.main]]
  identifier = "twitter"
  pre = "<i class='fab fa-twitter fa-lg'></i>"
  url = "https://twitter.com/mocobt"
  weight = 10

[[menu.main]]
  identifier = "blog"
  pre = "<i class='fa fa-pen-nib fa-lg'></i>"
  url = "https://mocobt.hatenablog.com/"
  weight = 20


[[menu.main]]
    identifier = "scrapbox"
    pre = "<i class='fab fa-stripe-s fa-lg'></i>"
    url = "https://scrapbox.io/HumanComputerInteraction/"
    weight = 30

[[menu.main]]
    identifier = "github"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/j20232"
    weight = 40

[[menu.main]]
    identifier = "kaggle"
    pre = "<i class='fab fa-kaggle fa-lg'></i>"
    url = "https://www.kaggle.com/noroaspe"
    weight = 45

[[menu.main]]
    identifier = "qiita"
    pre = "<i class='fas fa-search fa-lg'></i>"
    url = "https://qiita.com/mocobt"
    weight = 50

[[menu.main]]
  identifier = "Speaker Deck"
  pre = "<i class='fab fa-speaker-deck fa-lg'></i>"
  url = "https://speakerdeck.com/j20232"
  weight = 55

[[menu.main]]
    identifier = "email"
    # name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:mocobt@gmail.com"
    weight = 60
